# Generated by Django 3.0.7 on 2021-04-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idC', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cliente')),
                ('Nombre', models.CharField(max_length=20)),
                ('fecha_r', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.IntegerField(choices=[(10000, 'Perro                   $ 10000 '), (20000, 'Hamburguesa             $ 20000 '), (30000, 'Arroz                   $ 30000')], default=0)),
                ('Efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Devolucion', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha_p', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('id_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miregistro.Cliente', verbose_name='Cliente')),
            ],
        ),
    ]
