# Generated by Django 3.0.7 on 2021-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miregistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingrediente', models.IntegerField(choices=[('C', 'carne'), ('Q', 'queso'), ('P', 'pan')], default=0)),
                ('Cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
