# Generated by Django 3.0.7 on 2021-05-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miregistro', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
